-- Auto-generated by prep-gas on: 04-Apr-2023 13:36:17
-- Taken from eilmer/2D/ramjet-student-design fluid model file
model = 'CompositeGas'
species = {'O', 'O2', 'N2', 'H', 'H2', 'H2O', 'HO2', 'OH', 'H2O2', }

physical_model = 'thermally-perfect-gas'
energyModes = {'equilibrium'}
db = {}
db['O'] = {}
db['O'].atomicConstituents = { O=1, }
db['O'].charge = 0
db['O'].M = 1.59994000e-02
db['O'].sigma = 2.75000000
db['O'].epsilon = 80.00000000
db['O'].Lewis = 0.71200000
db['O'].thermoCoeffs = {
  origin = 'GRIMECH',
  nsegments = 2, 
  T_break_points = { 200.00, 1000.00, 3500.00, },
  T_blend_ranges = { 400.0, },
  segment0 = {
    0.000000000e+00,
    0.000000000e+00,
    3.168267100e+00,
   -3.279318840e-03,
    6.643063960e-06,
   -6.128066240e-09,
    2.112659710e-12,
    2.912225920e+04,
    2.051933460e+00,
  },
  segment1 = {
    0.000000000e+00,
    0.000000000e+00,
    2.569420780e+00,
   -8.597411370e-05,
    4.194845890e-08,
   -1.001777990e-11,
    1.228336910e-15,
    2.921757910e+04,
    4.784338640e+00,
  },
}
db['O'].viscosity = {
   model = 'Chemkin',
   nsegments = 1,
   segment0 = {
      T_lower = 200.0,
      T_upper = 3500.0,
      A = -1.7853144e+01,
      B =  2.1122060e+00,
      C = -1.9849765e-01,
      D =  8.9357862e-03,
   },
}
db['O'].thermal_conductivity = {
   model = 'Chemkin',
   nsegments = 1,
   segment0 = {
      T_lower = 200.0,
      T_upper = 3500.0,
      A = -1.0278188e+01,
      B =  2.1122058e+00,
      C = -1.9849761e-01,
      D =  8.9357842e-03,
   },
}
db['O2'] = {}
db['O2'].atomicConstituents = { O=2, }
db['O2'].charge = 0
db['O2'].M = 3.19988000e-02
db['O2'].sigma = 3.45800000
db['O2'].epsilon = 107.40000000
db['O2'].Lewis = 1.08600000
db['O2'].thermoCoeffs = {
  origin = 'GRIMECH',
  nsegments = 2, 
  T_break_points = { 200.00, 1000.00, 3500.00, },
  T_blend_ranges = { 400.0, },
  segment0 = {
    0.000000000e+00,
    0.000000000e+00,
    3.782456360e+00,
   -2.996734160e-03,
    9.847302010e-06,
   -9.681295090e-09,
    3.243728370e-12,
   -1.063943560e+03,
    3.657675730e+00,
  },
  segment1 = {
    0.000000000e+00,
    0.000000000e+00,
    3.282537840e+00,
    1.483087540e-03,
   -7.579666690e-07,
    2.094705550e-10,
   -2.167177940e-14,
   -1.088457720e+03,
    5.453231290e+00,
  },
}
db['O2'].viscosity = {
   model = 'Chemkin',
   nsegments = 1,
   segment0 = {
      T_lower = 200.0,
      T_upper = 3500.0,
      A = -2.0000567e+01,
      B =  2.8982604e+00,
      C = -3.0185111e-01,
      D =  1.3465402e-02,
   },
}
db['O2'].thermal_conductivity = {
   model = 'Chemkin',
   nsegments = 1,
   segment0 = {
      T_lower = 200.0,
      T_upper = 3500.0,
      A = -1.1722647e+01,
      B =  2.1844561e+00,
      C = -1.7561367e-01,
      D =  7.2718001e-03,
   },
}
db['N2'] = {}
db['N2'].atomicConstituents = { N=2, }
db['N2'].charge = 0
db['N2'].M = 2.80134000e-02
db['N2'].sigma = 3.62100000
db['N2'].epsilon = 97.53000000
db['N2'].Lewis = 1.15200000
db['N2'].thermoCoeffs = {
  origin = 'GRIMECH',
  nsegments = 2, 
  T_break_points = { 300.00, 1000.00, 5000.00, },
  T_blend_ranges = { 400.0, },
  segment0 = {
    0.000000000e+00,
    0.000000000e+00,
    3.298677000e+00,
    1.408240400e-03,
   -3.963222000e-06,
    5.641515000e-09,
   -2.444854000e-12,
   -1.020899900e+03,
    3.950372000e+00,
  },
  segment1 = {
    0.000000000e+00,
    0.000000000e+00,
    2.926640000e+00,
    1.487976800e-03,
   -5.684760000e-07,
    1.009703800e-10,
   -6.753351000e-15,
   -9.227977000e+02,
    5.980528000e+00,
  },
}
db['N2'].viscosity = {
   model = 'Chemkin',
   nsegments = 1,
   segment0 = {
      T_lower = 300.0,
      T_upper = 5000.0,
      A = -1.7567444e+01,
      B =  1.8193530e+00,
      C = -1.5171119e-01,
      D =  6.5201352e-03,
   },
}
db['N2'].thermal_conductivity = {
   model = 'Chemkin',
   nsegments = 1,
   segment0 = {
      T_lower = 300.0,
      T_upper = 5000.0,
      A = -4.1297647e+00,
      B = -1.0961963e+00,
      C =  2.9225955e-01,
      D = -1.4936361e-02,
   },
}
db['H'] = {}
db['H'].atomicConstituents = { H=1, }
db['H'].charge = 0
db['H'].M = 1.00794000e-03
db['H'].sigma = 2.05000000
db['H'].epsilon = 145.00000000
db['H'].Lewis = 0.18900000
db['H'].thermoCoeffs = {
  origin = 'GRIMECH',
  nsegments = 2, 
  T_break_points = { 200.00, 1000.00, 3500.00, },
  T_blend_ranges = { 400.0, },
  segment0 = {
    0.000000000e+00,
    0.000000000e+00,
    2.500000000e+00,
    7.053328190e-13,
   -1.995919640e-15,
    2.300816320e-18,
   -9.277323320e-22,
    2.547365990e+04,
   -4.466828530e-01,
  },
  segment1 = {
    0.000000000e+00,
    0.000000000e+00,
    2.500000010e+00,
   -2.308429730e-11,
    1.615619480e-14,
   -4.735152350e-18,
    4.981973570e-22,
    2.547365990e+04,
   -4.466829140e-01,
  },
}
db['H'].viscosity = {
   model = 'Chemkin',
   nsegments = 1,
   segment0 = {
      T_lower = 200.0,
      T_upper = 3500.0,
      A = -2.2876859e+01,
      B =  3.7093573e+00,
      C = -4.0386650e-01,
      D =  1.7741593e-02,
   },
}
db['H'].thermal_conductivity = {
   model = 'Chemkin',
   nsegments = 1,
   segment0 = {
      T_lower = 200.0,
      T_upper = 3500.0,
      A = -1.2537220e+01,
      B =  3.7093571e+00,
      C = -4.0386647e-01,
      D =  1.7741592e-02,
   },
}
db['H2'] = {}
db['H2'].atomicConstituents = { H=2, }
db['H2'].charge = 0
db['H2'].M = 2.01588000e-03
db['H2'].sigma = 2.92000000
db['H2'].epsilon = 38.00000000
db['H2'].Lewis = 0.31700000
db['H2'].thermoCoeffs = {
  origin = 'GRIMECH',
  nsegments = 2, 
  T_break_points = { 200.00, 1000.00, 3500.00, },
  T_blend_ranges = { 400.0, },
  segment0 = {
    0.000000000e+00,
    0.000000000e+00,
    2.344331120e+00,
    7.980520750e-03,
   -1.947815100e-05,
    2.015720940e-08,
   -7.376117610e-12,
   -9.179351730e+02,
    6.830102380e-01,
  },
  segment1 = {
    0.000000000e+00,
    0.000000000e+00,
    3.337279200e+00,
   -4.940247310e-05,
    4.994567780e-07,
   -1.795663940e-10,
    2.002553760e-14,
   -9.501589220e+02,
   -3.205023310e+00,
  },
}
db['H2'].viscosity = {
   model = 'Chemkin',
   nsegments = 1,
   segment0 = {
      T_lower = 200.0,
      T_upper = 3500.0,
      A = -1.6254105e+01,
      B =  1.0461640e+00,
      C = -5.5434974e-02,
      D =  2.5372766e-03,
   },
}
db['H2'].thermal_conductivity = {
   model = 'Chemkin',
   nsegments = 1,
   segment0 = {
      T_lower = 200.0,
      T_upper = 3500.0,
      A = -5.5406325e+00,
      B =  8.5588611e-01,
      C = -6.1350272e-02,
      D =  5.2136988e-03,
   },
}
db['H2O'] = {}
db['H2O'].atomicConstituents = { H=2, O=1, }
db['H2O'].charge = 0
db['H2O'].M = 1.80152800e-02
db['H2O'].sigma = 2.60500000
db['H2O'].epsilon = 572.40000000
db['H2O'].Lewis = 0.85400000
db['H2O'].thermoCoeffs = {
  origin = 'GRIMECH',
  nsegments = 2, 
  T_break_points = { 200.00, 1000.00, 3500.00, },
  T_blend_ranges = { 400.0, },
  segment0 = {
    0.000000000e+00,
    0.000000000e+00,
    4.198640560e+00,
   -2.036434100e-03,
    6.520402110e-06,
   -5.487970620e-09,
    1.771978170e-12,
   -3.029372670e+04,
   -8.490322080e-01,
  },
  segment1 = {
    0.000000000e+00,
    0.000000000e+00,
    3.033992490e+00,
    2.176918040e-03,
   -1.640725180e-07,
   -9.704198700e-11,
    1.682009920e-14,
   -3.000429710e+04,
    4.966770100e+00,
  },
}
db['H2O'].viscosity = {
   model = 'Chemkin',
   nsegments = 1,
   segment0 = {
      T_lower = 200.0,
      T_upper = 3500.0,
      A = -1.5962542e+01,
      B =  1.6789356e-01,
      C =  1.9290655e-01,
      D = -1.3567638e-02,
   },
}
db['H2O'].thermal_conductivity = {
   model = 'Chemkin',
   nsegments = 1,
   segment0 = {
      T_lower = 200.0,
      T_upper = 3500.0,
      A =  5.4160621e+00,
      B = -5.9686339e+00,
      C =  1.0912162e+00,
      D = -5.5363572e-02,
   },
}
db['HO2'] = {}
db['HO2'].atomicConstituents = { H=1, O=2, }
db['HO2'].charge = 0
db['HO2'].M = 3.30067400e-02
db['HO2'].sigma = 3.45800000
db['HO2'].epsilon = 107.40000000
db['HO2'].Lewis = 1.07900000
db['HO2'].thermoCoeffs = {
  origin = 'GRIMECH',
  nsegments = 2, 
  T_break_points = { 200.00, 1000.00, 3500.00, },
  T_blend_ranges = { 400.0, },
  segment0 = {
    0.000000000e+00,
    0.000000000e+00,
    4.301798010e+00,
   -4.749120510e-03,
    2.115828910e-05,
   -2.427638940e-08,
    9.292251240e-12,
    2.948080400e+02,
    3.716662450e+00,
  },
  segment1 = {
    0.000000000e+00,
    0.000000000e+00,
    4.017210900e+00,
    2.239820130e-03,
   -6.336581500e-07,
    1.142463700e-10,
   -1.079085350e-14,
    1.118567130e+02,
    3.785102150e+00,
  },
}
db['HO2'].viscosity = {
   model = 'Chemkin',
   nsegments = 1,
   segment0 = {
      T_lower = 200.0,
      T_upper = 3500.0,
      A = -1.9985060e+01,
      B =  2.8982601e+00,
      C = -3.0185107e-01,
      D =  1.3465400e-02,
   },
}
db['HO2'].thermal_conductivity = {
   model = 'Chemkin',
   nsegments = 1,
   segment0 = {
      T_lower = 200.0,
      T_upper = 3500.0,
      A = -9.0268160e+00,
      B =  7.7235987e-01,
      C =  6.2170816e-02,
      D = -4.9474803e-03,
   },
}
db['OH'] = {}
db['OH'].atomicConstituents = { H=1, O=1, }
db['OH'].charge = 0
db['OH'].M = 1.70073400e-02
db['OH'].sigma = 2.75000000
db['OH'].epsilon = 80.00000000
db['OH'].Lewis = 0.73600000
db['OH'].thermoCoeffs = {
  origin = 'GRIMECH',
  nsegments = 2, 
  T_break_points = { 200.00, 1000.00, 3500.00, },
  T_blend_ranges = { 400.0, },
  segment0 = {
    0.000000000e+00,
    0.000000000e+00,
    3.992015430e+00,
   -2.401317520e-03,
    4.617938410e-06,
   -3.881133330e-09,
    1.364114700e-12,
    3.615080560e+03,
   -1.039254580e-01,
  },
  segment1 = {
    0.000000000e+00,
    0.000000000e+00,
    3.092887670e+00,
    5.484297160e-04,
    1.265052280e-07,
   -8.794615560e-11,
    1.174123760e-14,
    3.858657000e+03,
    4.476696100e+00,
  },
}
db['OH'].viscosity = {
   model = 'Chemkin',
   nsegments = 1,
   segment0 = {
      T_lower = 200.0,
      T_upper = 3500.0,
      A = -1.7822598e+01,
      B =  2.1122057e+00,
      C = -1.9849760e-01,
      D =  8.9357837e-03,
   },
}
db['OH'].thermal_conductivity = {
   model = 'Chemkin',
   nsegments = 1,
   segment0 = {
      T_lower = 200.0,
      T_upper = 3500.0,
      A = -9.2451178e-01,
      B = -1.7602588e+00,
      C =  3.2957033e-01,
      D = -1.3990054e-02,
   },
}
db['H2O2'] = {}
db['H2O2'].atomicConstituents = { H=2, O=2, }
db['H2O2'].charge = 0
db['H2O2'].M = 3.40146800e-02
db['H2O2'].sigma = 3.45800000
db['H2O2'].epsilon = 107.40000000
db['H2O2'].Lewis = 1.15200000
db['H2O2'].thermoCoeffs = {
  origin = 'GRIMECH',
  nsegments = 2, 
  T_break_points = { 200.00, 1000.00, 3500.00, },
  T_blend_ranges = { 400.0, },
  segment0 = {
    0.000000000e+00,
    0.000000000e+00,
    4.276112690e+00,
   -5.428224170e-04,
    1.673357010e-05,
   -2.157708130e-08,
    8.624543630e-12,
   -1.770258210e+04,
    3.435050740e+00,
  },
  segment1 = {
    0.000000000e+00,
    0.000000000e+00,
    4.165002850e+00,
    4.908316940e-03,
   -1.901392250e-06,
    3.711859860e-10,
   -2.879083050e-14,
   -1.786178770e+04,
    2.916156620e+00,
  },
}
db['H2O2'].viscosity = {
   model = 'Chemkin',
   nsegments = 1,
   segment0 = {
      T_lower = 200.0,
      T_upper = 3500.0,
      A = -1.9970021e+01,
      B =  2.8982603e+00,
      C = -3.0185109e-01,
      D =  1.3465401e-02,
   },
}
db['H2O2'].thermal_conductivity = {
   model = 'Chemkin',
   nsegments = 1,
   segment0 = {
      T_lower = 200.0,
      T_upper = 3500.0,
      A = -9.2268132e+00,
      B =  7.2536302e-01,
      C =  1.0136660e-01,
      D = -8.2109734e-03,
   },
}
